on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: npm i
      - name: Git Config
        run: git config user.name "BuildBoio" && git config user.email "83129584+BuildBoio@users.noreply.github.com"
      - name: Build TS
        run: tsc
      - name: git branch
        run: git checkout prod
      - name: push
        run: git add . && git commit -m "build ts" && git push --set-upstream origin prod
